server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_activity?characterEncoding=utf-8&useSSL=false
    username: root
    password: root